version: '3.3'
services:
  php:
    image: 'php:fpm-alpine'
    restart: always
    build: .
    volumes:
      - './litchi:/code'
    expose:
      - 9000
    links:
      - db
  composer:
    image: library/composer
    restart: 'no'
    command: composer install
    volumes:
      - ./litchi:/app
    depends_on:
      - php
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    links:
      - db
  nginx:
    image: 'nginx:latest'
    restart: always
    ports:
      - '8000:80'
    volumes:
      - './litchi:/code'
      - './site-litchi.secondary.conf:/etc/nginx/conf.d/default.conf'
    links:
      - php
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 112481632
  node:
    image: "node:8"
    user: "node"
    working_dir: /code/src
    environment:
      - NODE_ENV=production
    volumes:
      - ./litchi:/code
    command: "npm run compile"
