version: '3.3'
services:
  php:
    image: 'php:fpm-alpine'
    build: .
    volumes:
      - './litchi:/code'
    expose:
      - 9000
    links:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    links:
      - db
  nginx:
    image: 'nginx:latest'
    ports:
      - '8000:80'
    volumes:
      - './litchi:/code'
      - './site-litchi.conf:/etc/nginx/conf.d/default.conf'
    links:
      - php
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 112481632
    
